image:
  repository: timberio/vector
  tag: latest-alpine
  pullPolicy: IfNotPresent

config: |-
  data_dir = "/var/lib/vector"

  [sources.kubernetes]
    type = "kubernetes"

  [transforms.json_parser]
    type = "json_parser"
    inputs = ["kubernetes"]
    drop_field = true
    field = "message"

  [sinks.es_cluster]
    inputs       = ["json_parser"]            # only take sampled data
    type         = "elasticsearch"
    host         = "http://es-logs.prod.pfm.internal"   # local or external host
    index        = "vector-%Y-%m-%d"             # daily indices
    request.rate_limit_num = 5000

resources:
  limits:
    cpu: 400m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 200Mi