image:
  repository: timberio/vector
  tag: 0.8.2-alpine
  pullPolicy: IfNotPresent

config: |-
  data_dir = "/var/lib/vector"
  [sources.kubernetes]
    type = "kubernetes"

  [transforms.json_parser]
    type = "json_parser"
    inputs = ["kubernetes"]
    drop_invalid = true
    drop_field = true
    field = "message"

  [sinks.es_cluster]
    inputs       = ["json_parser"]
    type         = "elasticsearch"
    host         = "http://es-logs.prod.pfm.internal"
    index        = "vector-%Y-%m-%d"
