apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "vector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "vector.name" . }}
    helm.sh/chart: {{ template "vector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "vector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ toYaml (.Values.config | sha256sum) }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $sec := .Values.image.pullSecrets }}
        - name: {{ $sec | quote }}
      {{- end }}
    {{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
{{- if .Values.extraInitContainers }}
      initContainers:
{{ toYaml .Values.extraInitContainers | indent 6 }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.command }}
        command:
{{ toYaml .Values.command | indent 8 }}
{{- end }}
        args:
{{- if .Values.args }}
{{ toYaml .Values.args | indent 8 }}
{{- else }}
{{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        securityContext:
          runAsUser: 0
{{- if .Values.privileged }}
          privileged: true
{{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector/vector.toml
          readOnly: true
          subPath: vector.toml
        - name: data
          mountPath: /var/lib/vector
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: vector-config
        secret:
          secretName: {{ template "vector.fullname" . }}
      - name: data
        hostPath:
          path: {{ .Values.data.hostPath }}
          type: DirectoryOrCreate
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
      terminationGracePeriodSeconds: 60
      serviceAccountName: {{ template "vector.serviceAccountName" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
