apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "vector.name" . }}
    helm.sh/chart: {{ template "vector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  vector.toml: {{ toYaml (.Values.config | b64enc) }}
  {{- if .Values.extraSecrets }}
  {{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end -}}

  {{ end }}
