{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vector.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "vector.name" . }}
    helm.sh/chart: {{ template "vector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
